@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.rudahee.metallics_arts.block.alloyfurnace;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;